In [1]:
import pandas as pd
df = pd.read_csv("homeprices.csv")

ModuleNotFoundError: No module named 'pandas'

In [ ]:
dummies = pd.get_dummies(df.town)

In [ ]:
merged = pd.concat([df, dummies], axis = 'columns')
merged.drop(['town', 'west windsor'], axis = 'columns', inplace = True)

In [ ]:
from sklearn.linear_model import LinearRegression
X = merged.drop(['price'], axis = 'columns')
y = merged.price
reg_model = LinearRegression().fit(X.values, y.values)

In [ ]:
reg_model.predict([[2800, 0, 1]])

array([590775.63964739])

In [ ]:
reg_model.score(X.values, y.values)

0.9573929037221873

In [ ]:
# With Sklearn LabelEncoder and OneHotEncoder()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df
dfle.town = le.fit_transform(dfle.town)
X = dfle[['town', 'area']].values
y = dfle.price

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough' 
)
X = ct.fit_transform(X)
X = X[:, 1:]

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [ ]:
reg_model.fit(X, y)

LinearRegression()

In [ ]:
reg_model.coef_

array([25686.4115244 , 40013.97548914,   126.89744141])

In [ ]:
reg_model.predict([[1, 0, 3400]])

array([666914.10449366])

In [ ]:
reg_model.score(X, y)

0.9573929037221874

# Exercise

In [ ]:
dfle = pd.read_csv('Exercise/carprices.csv')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
df = dfle.copy()
df['Car Model'] = LabelEncoder().fit_transform(df['Car Model'])
new_X = df[['Car Model', 'Mileage', 'Age(yrs)']].values
new_y = df['Sell Price($)']

In [ ]:
col_trans = ColumnTransformer([('one_hot_encoder', OneHotEncoder(categories = 'auto'), [0])], remainder = 'passthrough')
new_X = col_trans.fit_transform(new_X)

import numpy as np
from sklearn.linear_model import LinearRegression

new_X = np.delete(new_X, 1, 1)
reg_model = LinearRegression().fit(new_X, new_y)

array([-4.28466659e+03,  6.73820733e+03, -3.70122094e-01, -1.33245363e+03])

In [ ]:
reg_model.predict([[0,0, 4, 45000]])
reg_model.predict([[0, 1, 7, 86000]])

array([-1.14527753e+08])

In [ ]:
reg_model.score(new_X, new_y)

0.9417050937281083